export enum dbFailure{
  DB_FAILURE = "COULD NOT CONNECT TO DB",
  DB_WRITE_FAILURE = "COULD NOT WRITE TO DB",
  DB_READ_FAILURE = "COULD NOT READ FROM DB",
  DB_SEARCH_FAILURE = "COULD NOT FIND DB",
  DB_ITEM_NOT_FOUND = "ITEM NOT FOUND IN DB",
}

export enum rabbitFailure{
  RABBIT_URL_EMPTY = "RABBIT RECEIVED EMPTY CONNECTION URL",
  RABBIT_FAILURE = "COULD NOT SETUP RABBITMQ CONNECTION",
  RABBIT_CHANNEL_CREATION_FAILURE = "COULD NOT SETUP RABBITMQ CHANNEL",
  RABBIT_SEND_FAILURE = "COULD NOT SEND TO RABBITMQ QUEUE",
  RABBIT_CONSUMER_FAILURE = "CONSUMER CANCELLED BY SERVER",
  QUEUE_EMPTY = "RABBITMQ QUEUE IS EMPTY",
  QUEUE_MISSING = "RABBIRMQ QUEUE NOT DEFINED",
};

export enum paymentFailure{
  PAYMENT_FAILURE = "PAYMENT FAILED",
}

export enum shipmentFailure{
  SHIPMENT_FAILED = "SHIPMENT FAILED",
  SHIPMENT_STATUS_UNKNOWN = "SHIPMENT COULD NOT BE TRACKED",
}