export enum dbSuccess{
  DB_SUCCESS = "CONNECTED TO DB",
  DB_WRITE_SUCCESS = "DATA ADDED TO DB",
  DB_READ_SUCCESS = "READING FROM DB",
  DB_SEARCH_SUCCESS = "SEARCHING IN DB",
  DB_ITEM_NOT_FOUND = "ITEM FOUND IN DB",
}

export enum paymentSuccess{
  PAYMENT_SUCCESS = "PAYMENT PROCESSED",
}

export enum shipmentSuccess{
  SHIPMENT_SUCCESS = "SHIPPED SUCCESSFULLY",
}

export enum notifySuccess{
  NOTIFICATION_SUCCESS = "NOTIFICATION SENT SUCCESSFULLY",
}