export const DB_FAILURE = "COULD NOT CONNECT TO DB";
export const DB_WRITE_FAILURE = "COULD NOT WRITE TO DB";
export const DB_READ_FAILURE = "COULD NOT READ FROM DB";
export const DB_SEARCH_FAILURE = "COULD NOT FIND DB";
export const DB_ITEM_NOT_FOUND = "ITEM NOT FOUND IN DB";

export const RABBIT_FAILURE = "CONSUMER CANCELLED BY SERVER";
export const RABBIT_CONSUMER_FAILURE = "CONSUMER CANCELLED BY SERVER";

export const PAYMENT_FAILURE = "PAYMENT FAILED";